version: '3'
services:
  movies-api:
    depends_on:
      - mongo
    build:
      context: ./src/Movies.api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
  reviews-api:
    depends_on:
      - mongo
    build:
      context: ./src/Reviews.Api
      dockerfile: Dockerfile
    ports:
      - "32779:8080"
  
  mongo:
    image: mongo # use the latest image.
    container_name: mongodb
    restart: always
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: letterboxing
      MONGO_INITDB_ROOT_PASSWORD: letterboxing
    ports:
      - 27017:27017
    volumes: # optional to preserve database after container is deleted.
      - ./database-data:/data/db

  mongo-express:
    image: mongo-express # latest image
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: letterboxing
      ME_CONFIG_MONGODB_ADMINPASSWORD: letterboxing
      ME_CONFIG_MONGODB_URL: mongodb://letterboxing:letterboxing@mongodb:27017/


# rabbitmq:
#   image: "rabbitmq:3-management"
#   ports:
#     - "15672:15672"
#     - "5672:5672"
#   environment:
#     RABBITMQ_DEFAULT_USER: "guest"
#     RABBITMQ_DEFAULT_PASS: "guest"
#   volumes:
#     - rabbitmqdata:/var/lib/rabbitmq
      